### ISSUE TITLE
for...of is an ES6 feature

### ISSUE THREAD

**Issue by singingwolfboy** [lukasbuenger/immutable-treeutils#10]
In issue #9, @lukasbuenger decided to remove all ES6 features from this project. Unfortunately, it seems like [there is one ES6 feature remaining in the codebase](https://github.com/lukasbuenger/immutable-treeutils/blob/03ed2d046e5d8b211205f691a0901f86be2ca58d/index.js#L165). [`for...of`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/statements/for...of) was introduced in ES6, and as a result, it's still causing problems for UglifyJS (and presumably, other software that only works with ES5).

```
ERROR in application.js from UglifyJs
Unexpected token name «of», expected punc «;» [/Users/singingwolfboy/clones/impraise-web/node_modules/immutable-treeutils/index.js:165,0][application.js:215807,17]
```

Personally, I'm happy to switch to [`uglify-es`](https://www.npmjs.com/package/uglify-es), which is compatible with ES6, but since the author specifically made this change to avoid this kind of compatibility conflict, I wanted to raise this issue.

**Comment by lukasbuenger** [comment]
David, does the 1.0.1 work with your UglifyJS config again?
Many thanks for your feedback in advance.

**Comment by singingwolfboy** [comment]
1.0.1 works! Thank you 👍
