### ISSUE TITLE
babel6 supports

### ISSUE THREAD

**Issue by keit** [lukasbuenger/immutable-treeutils#2]
Hi, I just migrated to babel6. If you are interested in, i will send PR.

Thanks,
Kei

**Comment by lukasbuenger** [comment]
Hi Kei,

a PR would be most appreciated. I wanted to do this myself for some time, but my work kept me busy for the last couple of months.

Many thanks,
Lukas

**Comment by keit** [comment]
Hi Lukas,

I just sent a PR for babel6 migration. Please have a look.

Thanks,
Kei
