### ISSUE TITLE
[Improvement] Traversal type as option

### ISSUE THREAD

**Issue by jschlieber** [lukasbuenger/immutable-treeutils#7]
At the moment trees are always traversed in level order ([Breadth-first search](https://en.wikipedia.org/wiki/Breadth-first_search)). I propose to add an option to change the default [tree traversal type](https://en.wikipedia.org/wiki/Tree_traversal).

**Comment by lukasbuenger** [comment]
The `*nodes` iterator should be treated as unordered, even though that's not exactly true. It really is the only performance bottleneck in the whole library. If we gave the impression that `*nodes` iterates in a predictable manner, we'd lose the possibility to further optimize or completely replace the algorithm without breaking client expectations. 
I did quite some benchmarking on this one and the current implementation simply represents the fastest way of iterating over all nodes (that I was able to come up with at least). 

If you're simply looking for depth-first traversal, take a look at methods [right](https://github.com/lukasbuenger/immutable-treeutils#method-right) and [left](https://github.com/lukasbuenger/immutable-treeutils#method-left].
